name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install cwebp
      run: |
        apt-get update
        apt-get install webp -y
    - name: npm install, lint, and test
      run: |
        npm ci
        npm run lint
        npm test
      env:
        CI: true
