name: CICD
on: [push]
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install cwebp
      run: |
        sudo apt-get update
        sudo apt-get install webp -y

    - name: Install, Lint, and Test
      run: |
        npm ci
        npm run lint
        npm test
      env:
        CI: true

    - name: Deploy to Dev
      if: github.ref == 'refs/heads/dev'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm run build-layers
        npm run deploy-dev

    - name: Deploy to Prod
      if: github.ref == 'refs/heads/master'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        npm run build-layers
        npm run deploy-prod
      
